version: '3.8'

services:
  adonis_app:
    container_name: adonis_app
    restart: always
    build:
      context: .
      target: dependencies
    environment:
      APP_KEY: someverysecretkey
      APP_NAME: HealthCarePro
      SESSION_DRIVER: cookie
      DB_CONNECTION: sqlite
      SQLITE_FILE: ./tmp/db.sqlite
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    # env_file:
    #   - .env
    volumes:
      - ./:app
      # Uncomment the below line if you developing on MacOS
      #- app/node_modules
    command: dumb-init node ace serve --watch --node-args="--inspect=0.0.0.0"
  web:
    image: nginx
    container_name: nginx
    ports:
     - "80:80"
    volumes:
     - ./nginx/:/etc/nginx/conf.d/

#   db:
#     # Set DB version to run
#     image: postgres:13.3-alpine
#     # Restart container in case of crashes etc
#     restart: always
#     # Set DB to use host networking
#     network_mode: host
#     # Set DB env variables
#     environment:
#       POSTGRES_PASSWORD: example
#     # Mount DB data to volume, 
#     # so we don't lose all DB data over deployments
#     volumes:
#       - database:/var/lib/postgresql/data

# # Define the DB volume
# volumes:
#   database:
